language: csharp
mono:
 - alpha
 - beta
 - weekly
 - latest
 - 3.12.0
 - 3.10.0
 - 3.8.0
 - 3.2.8
 - 2.10.8
matrix:
 allow_failures:
  - mono: weekly
  - mono: alpha
  - mono: 3.2.8
  - mono: 2.10.8
solution: TranslationTable/TranslationTable.csproj